// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

// Injectors from wire.go:

func New(config Config) App {
	router := NewRouter(config)
	server := NewServer(router)
	captureCtl := NewCaptureCtl(config)
	app := NewApp(config, server, captureCtl)
	return app
}
