// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

// Injectors from wire.go:

func New() App {
	handler := NewRouter()
	server := NewServer(handler)
	app := NewApp(server)
	return app
}
